GOV.UK Prototype Kit compatibility
x-govuk/govuk-prototype-components pull request #58
Opened 2022-08-15 00:03 UTC by paulrobertlloyd

By using the GOV.UK Prototype Kit extension system, installing these prototype components is a much, much easier process.

This PR adds the requisite configuration file for this to work, and updates the usage instructions accordingly.

I have moved the documentation for decorated components to a separate section, but please take a look at the proposal in #57.

@jesseyuen: Does this address your feedback in #46?

2022-08-15 00:05 UTC, paulrobertlloyd commented
@fofr Can you also test that this works in your prototypes, as instructed? You can install via npm by pointing at this branch.

2022-08-17 08:34 UTC, fofr commented
Following this readme:
https://github.com/x-govuk/govuk-prototype-components/blob/eee44a37afba545a7d764adc7f0713b64b4bc5c7/README.md

And using this branch:
```
"govuk-prototype-components": "github:x-govuk/govuk-prototype-components#govuk-prototype-kit-compatibility"
```

The javascript is loaded correctly once I added the line.

The nunjucks macros are not loaded automatically, do they need to be added to layout.html? Or should it be automatic? There are no instructions about this.

2022-08-17 09:02 UTC, fofr requested changes
Add details on how to load all components to main README

2022-08-17 12:06 UTC, paulrobertlloyd commented
So, rather than show how to import *all* the components in the project README, I thought it made sense to show how to import an individual component alongside the Nunjucks for that component. This is for a few reasons:

* I imagine most authors would be interested in adding one or two components to a prototype, rather than all of them
* It shows all the Nunjucks code for a component in one place
* That the GOV.UK Prototype Kit places all imports in `layout.html` is an implementation detail

Bu, maybe I could add instructions to the main README to say that if you want to add all components to a prototype and have them available to all pages, place them in `layout.html` after the imports from `govuk-frontend`?

2022-08-17 13:23 UTC, fofr commented
Yes, I think just something which makes it clear they need to be imported and aren't available automatically.

2022-08-17 13:24 UTC, fofr commented
(I would personally just copy and paste the whole lot though, it's a prototype, for example – I don't go deleting any of the design system components I don't use)

2022-08-17 14:37 UTC, paulrobertlloyd commented
@fofr Take a look now.

2022-08-17 14:47 UTC, fofr approved these changes

2022-08-17 14:47 UTC, merged

2022-08-17 15:02 UTC, fofr commented
🎉